Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.


In [1]:
import numpy as np
arr = np.ones((10, 10), dtype=int) 
arr[1:-1, 1:-1] = 0
print(arr)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


2. Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.

In [2]:
print(np.tile([[0,1],[1,0]], (4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3. Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули

In [3]:
print(np.diagflat([1,2,3,4], -1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


4. Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее вдоль каждой строки было равно нулю.

5. Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.

In [4]:
arr = np.random.rand(10, 3)
print(arr[np.arange(10), np.argmin(np.abs(arr - 0.5), axis=1)])

[0.54342178 0.52624691 0.21412229 0.32400784 0.34352735 0.45848791
 0.63636164 0.47794593 0.70253299 0.3254688 ]


6. Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

In [5]:
arr = np.random.rand(6, 6)
print(arr.sum(axis=1) / arr.min(axis=0))

[ 12.62355531  76.44245279  20.23460299  16.12950499 165.95016107
  12.33426277]


7. На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [6]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print(np.max(x[(np.where(x == 0)[0] + 1) % 9]))

6


8. Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [8]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
print(np.bincount(i, minlength=len(x)) + x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


9. Задайте два массива a = np.array([[1, 4.9, 2.4], [7.1, 7, 9.8], [2, 4.6, 1.2]]) и b = np.array([3, 5, 10, 0]). Создайте массив, в котором каждый элемент первого массива заменен на ближайший к нему элемент второго массива.

In [9]:
a = np.array([[1, 4.9, 2.4], [7.1, 7, 9.8], [2, 4.6, 1.2]])
b = np.array([3, 5, 10, 0])
print(b[np.argmin(np.abs(a[:, :, None] - b), axis=2)])

[[ 0  5  3]
 [ 5  5 10]
 [ 3  5  0]]


10. Найдите скользящие средние с окном размера 3 по массиву a = np.array([1, 4.9, 2.4, 7.1, 7, 9.8, 2, -5, 4.6, 1.2]).

In [10]:
a = np.array([1, 4.9, 2.4, 7.1, 7, 9.8, 2, -5, 4.6, 1.2])
print(np.convolve(a, np.ones(3)/3, mode='valid'))

[2.76666667 4.8        5.5        7.96666667 6.26666667 2.26666667
 0.53333333 0.26666667]
